image: node:10.10.0

stages:
  - build

cache:
  paths:
    - node_modules/
    - ~/.nexe/

build:linux:
  stage: build
  script:
    - npm install
    - npm run build:package
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - bin/




