image: node:8.3.0

stages:
  - build
  - package

cache:
  paths:
    - node_modules/
    - /tmp/.nodec/

build:
  stage: build
  script:
    - npm install
    - npm run build:prod
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - dist/*

package:linux:
  stage: package
  script:
    - mkdir -p bin
    - curl -L http://enclose.io/nodec/nodec-linux-x64.gz | gunzip > nodec && chmod +x ./nodec
    - ./nodec dist/main.js --output=bin/auto-dns --tmpdir=/tmp/.nodec --keep-tmpdir
  artifacts:
    name: "linux"
    paths:
      - bin/auto-dns
