image: node:8

stages:
  - build

cache:
  paths:
    - node_modules/

build:linux:
  stage: build
  script:
    - npm install
    - npm run build:package
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - bin/




